language: node_js
node_js:
- '6'
before_install: npm install -g grunt-cli
install:
  - npm install
  - bower install
before_script: grunt
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: TownOfMarana/where-i-live
  bucket: marana-deploy
  region: us-west-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: marana-deploy
  key: latest.zip
  bundle_type: zip
  application: where-i-live
  deployment_group: production
  region: us-west-1
  on: *2
script:
  - cd dist
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
